[book]
authors = ["Shem Sedrick"]
language = "en"
multilingual = false
src = "src"
title = "ABCs of Programming"

[rust]
edition = "2018"

[build]
create-missing = false

[output.html]
additional-css = ['src/css/custom.css']
no-section-label = true
git-repository-url = 'https://github.com/ABCsOf/ABCs-of-Programming'

[preprocessor.page-styles.A.h1]
class = "aqua"

[preprocessor.page-styles.A.h2]
class = "orchid"
