name: Publish to Github Pages

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: github-pages
    - name: Merge Master
      run: git merge origin master

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: latest

    - name: Build
      run: mdbook build -d docs
    - name: Add
      run: git commit -am '$(git log -n1 --format=format:"%H")' && git push
    
