name: Publish to Github Pages

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get github-pages
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge Master
      run: git remote -v && git fetch origin github-pages && git checkout github-pages && git merge master

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: latest

    - name: Build
      run: mdbook build -d docs
    - name: Add
      run: git commit -am '$(git log -n1 --format=format:"%H")' && git push
    
